# Generated by Django 6.0.1 on 2026-02-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SudokuGame',
        ),
        migrations.AddField(
            model_name='gamescore',
            name='level',
            field=models.CharField(default='easy', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='time_taken',
            field=models.IntegerField(),
        ),
    ]
