# Generated by Django 6.0.1 on 2026-02-18 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_delete_sudokugame_gamescore_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamescore',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
    ]
